---
abstract: 'template based module starter for CGI apps.'
author:
  - 'Jaldhar H. Vyas <jaldhar@braincells.com>'
build_requires:
  File::Copy::Recursive: '0'
  File::DirCompare: '0'
  Test::MockTime: '0'
  Test::More: '0'
  Time::Piece: '1.12'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-Starter-Plugin-CGIApp
provides:
  Module::Starter::Plugin::CGIApp:
    file: lib/Module/Starter/Plugin/CGIApp.pm
    version: '0.44'
requires:
  File::ShareDir: '1.00'
  HTML::Template: '0'
  Module::Starter: '1.76'
  perl: '5.008'
resources:
  homepage: http://jaldhar.github.com/Module-Starter-Plugin-CGIApp/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jaldhar/Module-Starter-Plugin-CGIApp
version: '0.44'
